import React, { useState } from "react";

interface AuditLogItem {
  timestamp: string;
  eventId: string;
  actor: string;
  actorRole: string;
  initials: string;
  actorBg: string;
  actionTag: string;
  actionTagColor: string;
  candidateName: string;
  requisitionId: string;
  justification: string;
  cryptoHash: string;
}

export default function NotificationAuditLogCenter() {
  const [activeTab, setActiveTab] = useState("Operational Alerts & Tasks");
  const [currentPage, setCurrentPage] = useState(1);

  const auditLogs: AuditLogItem[] = [
    {
      timestamp: "14:28:10 UTC",
      eventId: "#EVT-8921",
      actor: "Alex Johnson",
      actorRole: "Lead Recruiter",
      initials: "AJ",
      actorBg: "bg-blue-600 text-white",
      actionTag: "MANUAL SCORE OVERRIDE",
      actionTagColor: "bg-blue-50 text-blue-700 border-blue-200",
      candidateName: "Harriet Lawrence",
      requisitionId: "#REQ-2026-084: Lead UX",
      justification:
        "Recruiter overridden AI match from 82% to 92% citing verified FinTech token systems experience.",
      cryptoHash: "0x8f2a...3c91",
    },
    {
      timestamp: "13:50:04 UTC",
      eventId: "#EVT-8920",
      actor: "Marcus Broadus",
      actorRole: "Senior Panelist",
      initials: "MB",
      actorBg: "bg-slate-200 text-slate-700",
      actionTag: "BATCH DISPATCH SIGN-OFF",
      actionTagColor: "bg-emerald-50 text-emerald-700 border-emerald-200",
      candidateName: "Batch #18 (12 Candidates)",
      requisitionId: "Engineering Track Requisitions",
      justification:
        "Validated customized feedback packages generated by Gemini 2.5. Released notifications to candidate portal.",
      cryptoHash: "0x3b1c...e408",
    },
    {
      timestamp: "12:15:33 UTC",
      eventId: "#EVT-8919",
      actor: "Alex Johnson",
      actorRole: "Lead Recruiter",
      initials: "AJ",
      actorBg: "bg-blue-600 text-white",
      actionTag: "AI RECOMMENDATION REJECTED",
      actionTagColor: "bg-rose-50 text-rose-700 border-rose-200",
      candidateName: "Devon Vance",
      requisitionId: "#REQ-2026-079: Staff Arch",
      justification:
        "Rejected auto-disqualification. Recruiter verified non-traditional open-source contributions surpass standard tenure checklist.",
      cryptoHash: "0x9d4e...11af",
    },
    {
      timestamp: "10:02:44 UTC",
      eventId: "#EVT-8918",
      actor: "Sarah Lin",
      actorRole: "Hiring VP",
      initials: "SL",
      actorBg: "bg-purple-100 text-purple-700",
      actionTag: "STAGE ADVANCEMENT",
      actionTagColor: "bg-slate-100 text-slate-700 border-slate-200",
      candidateName: "Elena Rostova",
      requisitionId: "#REQ-2026-093: AI Ops",
      justification:
        "Approved promotion to 'Offer Assembly' stage. Recruiter rationale noted 4/4 unanimous rubric score.",
      cryptoHash: "0x2e7f...882e",
    },
  ];

  return (
    <div className="flex-1 flex flex-col min-w-0 font-sans antialiased text-xs">
        {/* Top Navbar */}
        <header className="h-12 bg-white border-b border-slate-200 px-6 flex items-center justify-between shrink-0">
          <div className="flex items-center gap-2 text-slate-500 font-medium text-[11px]">
            <span>Workspace</span>
            <span>/</span>
            <span className="font-semibold text-slate-900">Notification &amp; Audit Log Center</span>
            <span className="flex items-center gap-1 ml-2 px-2 py-0.5 rounded-full border border-emerald-200 bg-emerald-50 text-emerald-700 text-[9px] font-semibold">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
              LIVE SYNC
            </span>
          </div>

          <div className="flex items-center gap-3">
            <div className="relative">
              <input
                type="text"
                placeholder="Search candidates by name, skill, requisition... ⌘K"
                className="w-72 h-7 pl-7 pr-3 text-[11px] bg-slate-50 rounded-md border border-slate-200 focus:outline-none focus:ring-1 focus:ring-blue-500"
              />
              <svg className="w-3.5 h-3.5 text-slate-400 absolute left-2 top-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
              </svg>
            </div>
            <button className="text-slate-400 hover:text-slate-600 relative">
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
              </svg>
              <span className="w-1.5 h-1.5 rounded-full bg-rose-500 absolute -top-0.5 -right-0.5" />
            </button>
            <button className="px-2.5 py-1 bg-blue-600 text-white font-semibold rounded hover:bg-blue-700 flex items-center gap-1">
              <span>+</span> Post New Job
            </button>
            <div className="w-6 h-6 rounded-full bg-blue-600 text-white font-bold flex items-center justify-center text-[10px]">
              AJ
            </div>
          </div>
        </header>

        {/* Content Body */}
        <main className="p-6 max-w-[1500px] w-full mx-auto space-y-4">
          {/* Header Action Bar */}
          <div className="flex items-start justify-between">
            <div>
              <div className="flex items-center gap-2">
                <h1 className="text-lg font-bold text-slate-900 leading-tight">
                  Notification &amp; Audit Log Center
                </h1>
                <span className="px-2 py-0.5 rounded bg-emerald-50 text-emerald-700 border border-emerald-200 text-[10px] font-bold">
                  🛡️ SYSTEM INTEGRITY: SECURE • AUDIT CHAIN: SYNCED (SHA-256)
                </span>
              </div>
              <p className="text-slate-500 text-xs mt-0.5">
                Monitor live operational alerts, SLA overdue risks, and immutable Human-in-the-Loop audit trails across requisitions.
              </p>
            </div>

            <div className="flex items-center gap-2">
              <select className="bg-white border border-slate-200 rounded-lg px-2.5 py-1.5 font-semibold text-slate-700 text-xs focus:outline-none">
                <option>REQ: #REQ-2026-084: Lead UX Researcher</option>
              </select>
              <button className="px-3 py-1.5 bg-white border border-slate-200 hover:bg-slate-50 text-slate-700 font-semibold rounded-lg flex items-center gap-1.5 shadow-sm">
                <span>✓</span> Mark All Read
              </button>
              <button className="px-3 py-1.5 bg-white border border-slate-200 hover:bg-slate-50 text-slate-700 font-semibold rounded-lg flex items-center gap-1.5 shadow-sm">
                <span>📥</span> Export Package (CSV/JSON)
              </button>
              <button className="p-1.5 bg-white border border-slate-200 text-slate-500 hover:bg-slate-50 rounded-lg">
                ⚙️️
              </button>
            </div>
          </div>

          {/* 4 Thẻ chỉ số tổng quan */}
          <div className="grid grid-cols-4 gap-4">
            <div className="bg-white border border-slate-200 rounded-xl p-3.5 shadow-sm flex items-start justify-between">
              <div>
                <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block">
                  ACTIVE ALERTS
                </span>
                <div className="flex items-baseline gap-1 mt-1">
                  <span className="text-2xl font-black text-slate-900">14 Unresolved</span>
                </div>
                <span className="text-[10px] text-rose-600 font-bold bg-rose-50 border border-rose-200 px-1.5 py-0.2 rounded mt-1.5 inline-block">
                  4 High Priority SLA Breaches
                </span>
              </div>
              <div className="w-7 h-7 rounded-lg bg-rose-50 text-rose-600 flex items-center justify-center font-bold text-xs">
                ⚠️
              </div>
            </div>

            <div className="bg-white border border-slate-200 rounded-xl p-3.5 shadow-sm flex items-start justify-between">
              <div>
                <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block">
                  RUBRIC &amp; EVALUATION SLAS
                </span>
                <div className="flex items-baseline gap-1 mt-1">
                  <span className="text-2xl font-black text-slate-900">98.2% On-Time</span>
                </div>
                <span className="text-[10px] text-slate-500 mt-1 block">
                  <strong className="text-emerald-600">↗ +1.4% vs last cycle</strong> • 2 overdue warnings
                </span>
              </div>
              <div className="w-7 h-7 rounded-lg bg-blue-50 text-blue-600 flex items-center justify-center font-bold text-xs">
                ⏱️
              </div>
            </div>

            <div className="bg-white border border-slate-200 rounded-xl p-3.5 shadow-sm flex items-start justify-between">
              <div>
                <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block">
                  HITL OVERRIDE DECISIONS
                </span>
                <div className="flex items-baseline gap-1 mt-1">
                  <span className="text-2xl font-black text-slate-900">27 Recorded</span>
                </div>
                <span className="text-[10px] text-slate-500 mt-1 block">
                  100% justified with recruiter rationale
                </span>
              </div>
              <div className="w-7 h-7 rounded-lg bg-slate-100 text-slate-600 flex items-center justify-center font-bold text-xs">
                📑
              </div>
            </div>

            <div className="bg-white border border-slate-200 rounded-xl p-3.5 shadow-sm flex items-start justify-between">
              <div>
                <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block">
                  AUDIT COMPLIANCE SCORE
                </span>
                <div className="flex items-baseline gap-1 mt-1">
                  <span className="text-2xl font-black text-slate-900">99.8%</span>
                </div>
                <span className="text-[10px] text-emerald-600 font-semibold mt-1 flex items-center gap-1">
                  ✓ DEI Bias-Free &amp; SOC2 Type II verified
                </span>
              </div>
              <div className="w-7 h-7 rounded-lg bg-emerald-50 text-emerald-600 flex items-center justify-center font-bold text-xs">
                🛡️
              </div>
            </div>
          </div>

          {/* Tab điều hướng phân loại alert */}
          <div className="flex items-center justify-between border-b border-slate-200 pb-2 text-xs">
            <div className="flex items-center gap-2">
              <button
                onClick={() => setActiveTab("Operational Alerts & Tasks")}
                className={`px-3 py-1.5 rounded-lg font-bold transition flex items-center gap-1.5 ${
                  activeTab === "Operational Alerts & Tasks"
                    ? "bg-blue-50 text-blue-700 border border-blue-200 shadow-sm"
                    : "text-slate-600 hover:bg-slate-50"
                }`}
              >
                <span>🔔 Operational Alerts &amp; Tasks</span>
                <span className="px-1.5 py-0.2 rounded-full bg-rose-500 text-white text-[9px] font-bold">14</span>
              </button>
              <button
                onClick={() => setActiveTab("Governance & Immutable Audit Trail")}
                className={`px-3 py-1.5 rounded-lg font-semibold transition flex items-center gap-1.5 ${
                  activeTab === "Governance & Immutable Audit Trail"
                    ? "bg-blue-50 text-blue-700 border border-blue-200 shadow-sm"
                    : "text-slate-600 hover:bg-slate-50"
                }`}
              >
                <span>📜 Governance &amp; Immutable Audit Trail</span>
                <span className="px-1.5 py-0.2 rounded-full bg-slate-200 text-slate-600 text-[9px]">1,248</span>
              </button>
              <button
                onClick={() => setActiveTab("Compliance & SLA Matrix")}
                className={`px-3 py-1.5 rounded-lg font-semibold transition ${
                  activeTab === "Compliance & SLA Matrix"
                    ? "bg-blue-50 text-blue-700 border border-blue-200 shadow-sm"
                    : "text-slate-600 hover:bg-slate-50"
                }`}
              >
                📊 Compliance &amp; SLA Matrix
              </button>
            </div>

            <div className="flex items-center gap-2">
              <div className="relative">
                <input
                  type="text"
                  placeholder="Filter alerts or panelist..."
                  className="w-48 h-7 pl-6 pr-2 bg-white border border-slate-200 rounded-md text-[11px] focus:outline-none"
                />
                <span className="text-slate-400 absolute left-2 top-1.5 text-[10px]">🔍</span>
              </div>
              <button className="h-7 px-2.5 bg-white border border-slate-200 rounded-md text-slate-700 font-semibold flex items-center gap-1 text-[11px]">
                <span>📅</span> Last 24 Hours
              </button>
            </div>
          </div>

          {/* Lưới 2 Cột: Urgent Human-In-The-Loop Actions (7/12) & Audit Event Deep-Dive (5/12) */}
          <div className="grid grid-cols-12 gap-5 items-start">
            {/* Cột Trái: Urgent Actions (7/12) */}
            <div className="col-span-7 space-y-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <span className="font-bold text-slate-900 text-xs">
                    Urgent Human-In-The-Loop Actions
                  </span>
                  <span className="px-1.5 py-0.2 rounded bg-blue-100 text-blue-700 font-bold text-[9px]">
                    SLA ENGINE ACTIVE
                  </span>
                </div>
                <span className="text-[10px] text-slate-400">Ordered by Escalation Urgency</span>
              </div>

              {/* Alert 1: Red Priority */}
              <div className="bg-white border border-slate-200 rounded-xl p-4 shadow-sm border-l-4 border-l-rose-500 space-y-2">
                <div className="flex items-start justify-between">
                  <div className="flex items-start gap-2.5">
                    <span className="text-rose-500 font-bold text-sm mt-0.5">⚠️</span>
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="font-bold text-slate-900 text-xs">
                          Interview Rubric Overdue (4.2h elapsed)
                        </span>
                        <span className="px-1.5 py-0.2 bg-rose-50 text-rose-700 border border-rose-200 rounded text-[9px] font-bold">
                          Critical SLA Breach
                        </span>
                      </div>
                      <p className="text-slate-600 text-[11px] mt-0.5">
                        Panel member <strong>Marcus Broadus (Senior Backend Dev)</strong> has not submitted qualitative rubric scores for candidate{" "}
                        <strong className="text-blue-600">Harriet Lawrence</strong> (Round 2 Architecture Sync).
                      </p>
                    </div>
                  </div>
                  <span className="text-[10px] text-slate-400 whitespace-nowrap">12 min ago</span>
                </div>

                <div className="flex items-center justify-between pt-2 border-t border-slate-100 text-[10px]">
                  <span className="text-slate-500">
                    📍 Requisition: #REQ-2026-084 • SLA Target: 2.0h Post-Interview
                  </span>
                  <div className="flex items-center gap-2">
                    <button className="px-2.5 py-1 bg-white border border-slate-200 text-slate-700 hover:bg-slate-50 font-semibold rounded flex items-center gap-1">
                      <span>✈️</span> Send Slack Ping
                    </button>
                    <button className="px-2.5 py-1 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded">
                      Reassign Panelist
                    </button>
                  </div>
                </div>
              </div>

              {/* Alert 2: Blue Priority */}
              <div className="bg-white border border-slate-200 rounded-xl p-4 shadow-sm border-l-4 border-l-blue-600 space-y-2">
                <div className="flex items-start justify-between">
                  <div className="flex items-start gap-2.5">
                    <span className="text-blue-600 font-bold text-sm mt-0.5">🤖</span>
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="font-bold text-slate-900 text-xs">
                          AI Feedback Drafts Ready (3 Pending Review)
                        </span>
                        <span className="px-1.5 py-0.2 bg-blue-50 text-blue-700 border border-blue-200 rounded text-[9px] font-bold">
                          Gemini 2.5 Flash
                        </span>
                      </div>
                      <p className="text-slate-600 text-[11px] mt-0.5">
                        Post-interview evaluation transcripts synthesized. AI has produced constructive candidate feedback drafts requiring lead recruiter validation before dispatch.
                      </p>
                    </div>
                  </div>
                  <span className="text-[10px] text-slate-400 whitespace-nowrap">46 min ago</span>
                </div>

                <div className="flex items-center justify-between pt-2 border-t border-slate-100 text-[10px]">
                  <span className="text-emerald-700 font-semibold">
                    ✓ Guardrails: 0 Hallucinations Detected • PII Masked
                  </span>
                  <button className="px-3 py-1 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded flex items-center gap-1">
                    <span>📄</span> Review in Dispatch Studio
                  </button>
                </div>
              </div>

              {/* Alert 3: Amber Priority */}
              <div className="bg-white border border-slate-200 rounded-xl p-4 shadow-sm border-l-4 border-l-amber-500 space-y-2">
                <div className="flex items-start justify-between">
                  <div className="flex items-start gap-2.5">
                    <span className="text-amber-500 font-bold text-sm mt-0.5">👥</span>
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="font-bold text-slate-900 text-xs">
                          Candidate Inflow Spike (+42 applicants)
                        </span>
                        <span className="px-1.5 py-0.2 bg-amber-50 text-amber-700 border border-amber-200 rounded text-[9px] font-bold">
                          Capacity Risk
                        </span>
                      </div>
                      <p className="text-slate-600 text-[11px] mt-0.5">
                        Requisition #REQ-2026-084 surged to 142 total submissions in the past 6 hours following LinkedIn Campaign #UX-Q3. Auto-triage recommends batch screening.
                      </p>
                    </div>
                  </div>
                  <span className="text-[10px] text-slate-400 whitespace-nowrap">1h 14m ago</span>
                </div>

                <div className="flex items-center justify-between pt-2 border-t border-slate-100 text-[10px]">
                  <span className="text-slate-500">
                    Recommended Action: Apply automated semantic resume matching filter
                  </span>
                  <button className="px-2.5 py-1 bg-white border border-slate-200 text-slate-700 hover:bg-slate-50 font-semibold rounded flex items-center gap-1">
                    <span>⚡</span> Launch Screening Hub
                  </button>
                </div>
              </div>

              {/* Alert 4: Green Verified */}
              <div className="bg-white border border-slate-200 rounded-xl p-4 shadow-sm border-l-4 border-l-emerald-500 space-y-1">
                <div className="flex items-start justify-between">
                  <div className="flex items-start gap-2.5">
                    <span className="text-emerald-600 font-bold text-sm mt-0.5">🛡️</span>
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="font-bold text-slate-900 text-xs">
                          Blind Triage Verification Passed
                        </span>
                        <span className="px-1.5 py-0.2 bg-emerald-50 text-emerald-700 border border-emerald-200 rounded text-[9px] font-bold">
                          DEI Guard Validated
                        </span>
                      </div>
                      <p className="text-slate-600 text-[11px] mt-0.5">
                        100% of demographic variables (Age, Gender, Location, Alma Mater) sanitized across Batch #4 candidates. EEOC compliance certificate signed for audit payload.
                      </p>
                    </div>
                  </div>
                  <span className="text-[10px] text-slate-400 whitespace-nowrap">2h ago</span>
                </div>
              </div>
            </div>

            {/* Cột Phải: Audit Event Deep-Dive (5/12) */}
            <div className="col-span-5 bg-white border border-slate-200 rounded-xl p-4 shadow-sm space-y-3">
              <div className="flex items-center justify-between border-b border-slate-100 pb-2">
                <h2 className="font-bold text-slate-900 text-xs">
                  Audit Event Deep-Dive: #EVT-8921
                </h2>
                <span className="px-1.5 py-0.2 rounded bg-emerald-50 text-emerald-700 border border-emerald-200 text-[9px] font-bold">
                  Tamper-Proof Block
                </span>
              </div>

              {/* Actor Header */}
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2.5">
                  <div className="w-8 h-8 rounded-full bg-blue-600 text-white font-bold flex items-center justify-center text-xs">
                    AJ
                  </div>
                  <div>
                    <span className="font-bold text-slate-900 text-xs block leading-tight">
                      Alex Johnson (Lead Recruiter)
                    </span>
                    <span className="text-[10px] text-slate-500 block">
                      Action: MANUAL SCORE OVERRIDE • Authenticated
                    </span>
                  </div>
                </div>
                <span className="text-[10px] font-mono text-slate-400">IP: 198.51.100.42</span>
              </div>

              {/* Side-by-side comparison */}
              <div className="grid grid-cols-2 gap-2 text-[11px]">
                <div className="bg-slate-50 border border-slate-200 rounded-lg p-2.5 space-y-1">
                  <span className="text-[9px] font-bold text-slate-400 uppercase tracking-wider block">
                    ORIGINAL AI SUGGESTION
                  </span>
                  <span className="font-bold text-slate-800 text-xs block">82% Match</span>
                  <p className="text-[10px] text-slate-500 leading-tight">
                    Penalized: Missing Figma Design System Token keyword
                  </p>
                </div>

                <div className="bg-blue-50/70 border border-blue-200 rounded-lg p-2.5 space-y-1">
                  <span className="text-[9px] font-bold text-blue-600 uppercase tracking-wider block">
                    RECRUITER MANUAL OVERRIDE
                  </span>
                  <span className="font-bold text-blue-700 text-xs block">92% High Match</span>
                  <p className="text-[10px] text-blue-600 leading-tight">
                    Verified 4yr FinTech design system leadership portfolio
                  </p>
                </div>
              </div>

              {/* Recruiter Signed Rationale */}
              <div className="space-y-1 text-[11px]">
                <span className="text-[9px] font-bold text-slate-400 uppercase tracking-wider block">
                  RECRUITER SIGNED RATIONALE
                </span>
                <p className="p-2 bg-slate-50 border border-slate-200 rounded text-slate-700 italic leading-relaxed text-[11px]">
                  "Candidate Harriet Lawrence maintained proprietary design token schemas at Stripe-equivalent fintech scale. AI parsing failed on proprietary JSON token schema naming convention. Manual portfolio validation confirms tier-1 mastery."
                </p>
              </div>

              {/* Cryptographic Block Chain Info */}
              <div className="bg-slate-50 border border-slate-200 rounded-lg p-2.5 space-y-1 text-[10px] font-mono">
                <div className="flex justify-between">
                  <span className="text-slate-400">BLOCK HEIGHT / SEQUENCE:</span>
                  <span className="font-bold text-slate-700">#144,928 • Chain Layer 2</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-400">SHA-256 CHECKSUM:</span>
                  <span className="text-blue-600 font-bold truncate max-w-[200px]">
                    0x8f2a910bf72ca9e8...3c91
                  </span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-400">VERIFICATION STATUS:</span>
                  <span className="text-emerald-600 font-bold">✓ Valid &amp; Immutable</span>
                </div>
              </div>

              {/* Historical Pipeline Snapshot */}
              <div className="space-y-1">
                <span className="text-[9px] font-bold text-slate-400 uppercase tracking-wider block">
                  HISTORICAL PIPELINE SNAPSHOT
                </span>
                <div className="border border-slate-200 rounded-lg p-2 bg-slate-100 flex items-center justify-between text-[10px]">
                  <div className="flex items-center gap-2">
                    <span className="font-mono text-slate-600">smartrecruit-manager-operations-dashboard</span>
                  </div>
                  <span className="px-1 bg-white border border-slate-200 rounded text-slate-500 font-bold text-[9px]">
                    Snapshot (Oct 2026)
                  </span>
                </div>
              </div>

              {/* Actions Footer */}
              <div className="flex items-center justify-between pt-1 text-[11px]">
                <button className="text-slate-600 hover:text-blue-600 font-semibold flex items-center gap-1">
                  <span>📥</span> Download Cryptographic Receipt
                </button>
                <button className="px-2.5 py-1 bg-blue-600 text-white font-bold rounded flex items-center gap-1 shadow-sm">
                  <span>Inspect Raw JSON</span> ↗
                </button>
              </div>
            </div>
          </div>

          {/* Bảng Dưới: Recruiter Governance & HITL Decision Log */}
          <div className="bg-white border border-slate-200 rounded-xl overflow-hidden shadow-sm space-y-0">
            <div className="p-4 border-b border-slate-200 flex items-center justify-between">
              <div>
                <h2 className="font-bold text-slate-900 text-xs flex items-center gap-2">
                  <span>📜</span> Recruiter Governance &amp; HITL Decision Log
                </h2>
                <p className="text-[10px] text-slate-400 mt-0.5">
                  Chronological immutable event ledger tracking human overrides, stage advancements, and AI dispatches.
                </p>
              </div>

              <div className="flex items-center gap-3">
                <div className="relative">
                  <input
                    type="text"
                    placeholder="Search by Actor, Candidate ID, Action, Hash..."
                    className="w-80 h-7 pl-7 pr-3 bg-slate-50 border border-slate-200 rounded-md text-[11px] focus:outline-none"
                  />
                  <span className="text-slate-400 absolute left-2 top-1.5 text-[10px]">🔍</span>
                </div>
                <span className="flex items-center gap-1 text-emerald-600 font-bold text-[10px]">
                  ● Live Stream: Active
                </span>
              </div>
            </div>

            {/* Table Header */}
            <div className="grid grid-cols-12 px-4 py-2 border-b border-slate-200 bg-slate-50 text-[10px] font-bold text-slate-400 uppercase tracking-wider">
              <div className="col-span-2">TIMESTAMP &amp; EVENT ID</div>
              <div className="col-span-2">ACTOR / RECRUITER</div>
              <div className="col-span-2">ACTION CLASSIFICATION</div>
              <div className="col-span-2">CANDIDATE / REQUISITION</div>
              <div className="col-span-3">JUSTIFICATION &amp; RECRUITER RATIONALE</div>
              <div className="col-span-1 text-right">VERIFICATION</div>
            </div>

            {/* Danh sách Audit Logs */}
            <div className="divide-y divide-slate-100">
              {auditLogs.map((log) => (
                <div key={log.eventId} className="grid grid-cols-12 px-4 py-3 items-center hover:bg-slate-50 transition text-[11px]">
                  <div className="col-span-2 leading-tight">
                    <span className="font-bold text-slate-900 block">{log.timestamp}</span>
                    <span className="text-[10px] font-mono text-slate-400">{log.eventId}</span>
                  </div>

                  <div className="col-span-2 flex items-center gap-2">
                    <div className={`w-6 h-6 rounded-full font-bold flex items-center justify-center text-[9px] shrink-0 ${log.actorBg}`}>
                      {log.initials}
                    </div>
                    <div className="min-w-0">
                      <span className="font-semibold text-slate-900 block truncate leading-tight">{log.actor}</span>
                      <span className="text-[10px] text-slate-400 block truncate">{log.actorRole}</span>
                    </div>
                  </div>

                  <div className="col-span-2">
                    <span className={`inline-block px-1.5 py-0.5 rounded text-[9px] font-bold border ${log.actionTagColor}`}>
                      {log.actionTag}
                    </span>
                  </div>

                  <div className="col-span-2 leading-tight">
                    <span className="font-bold text-slate-900 block truncate">{log.candidateName}</span>
                    <span className="text-[10px] text-slate-400 block truncate">{log.requisitionId}</span>
                  </div>

                  <div className="col-span-3 pr-4 leading-tight">
                    <p className="text-slate-600 line-clamp-2 text-[11px]">{log.justification}</p>
                    <span className="text-[9px] font-mono text-slate-400 mt-0.5 block">{log.cryptoHash}</span>
                  </div>

                  <div className="col-span-1 text-right">
                    <button className="px-2 py-1 bg-white border border-slate-200 text-blue-600 hover:bg-slate-50 font-bold rounded text-[10px] shadow-sm">
                      Dossier
                    </button>
                  </div>
                </div>
              ))}
            </div>

            {/* Phân trang Footer */}
            <div className="px-4 py-2.5 border-t border-slate-200 flex items-center justify-between text-[11px] text-slate-500 bg-white">
              <span>
                Showing 1 to 4 of 1,248 immutable records • Latency: 14ms (Distributed Ledger Node)
              </span>

              <div className="flex items-center gap-1 font-semibold">
                <button className="px-2 py-0.5 border rounded hover:bg-slate-50 text-slate-400">Previous</button>
                <button className="px-2 py-0.5 rounded bg-blue-600 text-white font-bold">1</button>
                <button className="px-2 py-0.5 rounded hover:bg-slate-100">2</button>
                <button className="px-2 py-0.5 rounded hover:bg-slate-100">3</button>
                <span>...</span>
                <button className="px-2 py-0.5 rounded hover:bg-slate-100">312</button>
                <button className="px-2 py-0.5 border rounded hover:bg-slate-50">Next</button>
              </div>
            </div>
          </div>
        </main>
    </div>
  );
}