function updatePertSmartRecruit() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = ss.getSheetByName("PERT_SmartRecruit");
  if (!sheet) { sheet = ss.insertSheet("PERT_SmartRecruit"); }

  sheet.getRange("B1").setValue("3.4.1 - SƠ ĐỒ PERT CHO CÔNG VIỆC PHÂN TÍCH, XỬ LÝ YÊU CẦU DỰ ÁN SMARTRECRUIT");
  sheet.getRange("B2").setValue("Giai đoạn 1: Phác thảo cơ sở dữ liệu SmartRecruit");
  sheet.getRange("I2").setValue("Giai đoạn 2: Phác thảo các giao diện");
  sheet.getRange("J2").setValue("Giai đoạn 2: Phác thảo các giao diện SmartRecruit");
  sheet.getRange("R2").setValue("Giai đoạn 3: Phác thảo các chức năng SmartRecruit");
  sheet.getRange("J4").setValue("E");
  sheet.getRange("N4").setValue("H");
  sheet.getRange("R4").setValue("K");
  sheet.getRange("J5").setValue(4);
  sheet.getRange("K5").setValue(1);
  sheet.getRange("L5").setValue(5);
  sheet.getRange("N5").setValue(6);
  sheet.getRange("O5").setValue(1);
  sheet.getRange("P5").setValue(7);
  sheet.getRange("R5").setValue(8);
  sheet.getRange("S5").setValue(1);
  sheet.getRange("T5").setValue(9);
  sheet.getRange("J6").setValue("3.1.2.1 - Phác thảo trang chủ & Landing Page");
  sheet.getRange("N6").setValue("3.1.2.4 - Phác thảo trang nộp CV & parse AI");
  sheet.getRange("R6").setValue("3.1.3.1 - Phát thảo chức năng xác thực RBAC");
  sheet.getRange("B7").setValue("A");
  sheet.getRange("F7").setValue("C");
  sheet.getRange("J7").setValue(12);
  sheet.getRange("K7").setValue(8);
  sheet.getRange("L7").setValue(13);
  sheet.getRange("N7").setValue(12);
  sheet.getRange("O7").setValue(6);
  sheet.getRange("P7").setValue(13);
  sheet.getRange("R7").setValue(12);
  sheet.getRange("S7").setValue(4);
  sheet.getRange("T7").setValue(13);
  sheet.getRange("B8").setValue(0);
  sheet.getRange("C8").setValue(2);
  sheet.getRange("D8").setValue(2);
  sheet.getRange("F8").setValue(2);
  sheet.getRange("G8").setValue(1);
  sheet.getRange("H8").setValue(3);
  sheet.getRange("B9").setValue("3.1.1.1 - Sơ đồ Use Case SmartRecruit");
  sheet.getRange("F9").setValue("3.1.1.3 - Sơ đồ luồng dữ liệu - DFD SmartRecruit");
  sheet.getRange("B10").setValue(0);
  sheet.getRange("C10").setValue(0);
  sheet.getRange("D10").setValue(2);
  sheet.getRange("F10").setValue(12);
  sheet.getRange("G10").setValue(10);
  sheet.getRange("H10").setValue(13);
  sheet.getRange("J10").setValue("F");
  sheet.getRange("N10").setValue("I");
  sheet.getRange("R10").setValue("L");
  sheet.getRange("V10").setValue("N");
  sheet.getRange("J11").setValue(4);
  sheet.getRange("K11").setValue(1);
  sheet.getRange("L11").setValue(5);
  sheet.getRange("N11").setValue(6);
  sheet.getRange("O11").setValue(1);
  sheet.getRange("P11").setValue(7);
  sheet.getRange("R11").setValue(8);
  sheet.getRange("S11").setValue(2);
  sheet.getRange("T11").setValue(10);
  sheet.getRange("V11").setValue(11);
  sheet.getRange("W11").setValue(1);
  sheet.getRange("X11").setValue(12);
  sheet.getRange("J12").setValue("3.1.2.2 - Phác thảo trang đăng nhập & OIDC");
  sheet.getRange("N12").setValue("3.1.2.5 - Phác thảo trang ranking ứng viên");
  sheet.getRange("R12").setValue("3.1.3.2 - Phát thảo chức năng lưu trữ CV S3");
  sheet.getRange("V12").setValue("3.1.3.4 - Phát thảo chức năng đánh giá & rubric");
  sheet.getRange("B13").setValue("B");
  sheet.getRange("F13").setValue("D");
  sheet.getRange("J13").setValue(12);
  sheet.getRange("K13").setValue(8);
  sheet.getRange("L13").setValue(13);
  sheet.getRange("N13").setValue(12);
  sheet.getRange("O13").setValue(6);
  sheet.getRange("P13").setValue(13);
  sheet.getRange("R13").setValue(11);
  sheet.getRange("S13").setValue(3);
  sheet.getRange("T13").setValue(13);
  sheet.getRange("V13").setValue(12);
  sheet.getRange("W13").setValue(1);
  sheet.getRange("X13").setValue(13);
  sheet.getRange("B14").setValue(0);
  sheet.getRange("C14").setValue(1);
  sheet.getRange("D14").setValue(1);
  sheet.getRange("F14").setValue(2);
  sheet.getRange("G14").setValue(2);
  sheet.getRange("H14").setValue(4);
  sheet.getRange("B15").setValue("3.1.1.2 - Sơ đồ Class / Domain Model");
  sheet.getRange("F15").setValue("3.1.1.4 - Sơ đồ thực thể kết hợp - ERD 16 bảng");
  sheet.getRange("B16").setValue(1);
  sheet.getRange("C16").setValue(1);
  sheet.getRange("D16").setValue(2);
  sheet.getRange("F16").setValue(2);
  sheet.getRange("G16").setValue(0);
  sheet.getRange("H16").setValue(4);
  sheet.getRange("J16").setValue("G");
  sheet.getRange("N16").setValue("J");
  sheet.getRange("R16").setValue("M");
  sheet.getRange("V16").setValue("O");
  sheet.getRange("J17").setValue(4);
  sheet.getRange("K17").setValue(2);
  sheet.getRange("L17").setValue(6);
  sheet.getRange("N17").setValue(6);
  sheet.getRange("O17").setValue(2);
  sheet.getRange("P17").setValue(8);
  sheet.getRange("R17").setValue(8);
  sheet.getRange("S17").setValue(3);
  sheet.getRange("T17").setValue(11);
  sheet.getRange("V17").setValue(11);
  sheet.getRange("W17").setValue(2);
  sheet.getRange("X17").setValue(13);
  sheet.getRange("J18").setValue("3.1.2.3 - Phác thảo trang quản lý tin (Job)");
  sheet.getRange("N18").setValue("3.1.2.6 - Phác thảo Dashboard thống kê phễu");
  sheet.getRange("R18").setValue("3.1.3.3 - Phát thảo chức năng Gemini & Match");
  sheet.getRange("V18").setValue("3.1.3.5 - Phát thảo chức năng báo cáo KPI");
  sheet.getRange("J19").setValue(4);
  sheet.getRange("K19").setValue(0);
  sheet.getRange("L19").setValue(6);
  sheet.getRange("N19").setValue(6);
  sheet.getRange("O19").setValue(0);
  sheet.getRange("P19").setValue(8);
  sheet.getRange("R19").setValue(8);
  sheet.getRange("S19").setValue(0);
  sheet.getRange("T19").setValue(11);
  sheet.getRange("V19").setValue(11);
  sheet.getRange("W19").setValue(0);
  sheet.getRange("X19").setValue(13);
  sheet.getRange("B24").setValue("STT");
  sheet.getRange("C24").setValue("Đường công việc");
  sheet.getRange("I24").setValue("Tổng");
  sheet.getRange("K24").setValue("Dựa vào 18 đường công việc, ta xác định được đường GANTT / PERT thiết yếu (Đường găng CPM) như sau:");
  sheet.getRange("B25").setValue(1);
  sheet.getRange("C25").setValue("A(2)");
  sheet.getRange("D25").setValue("C(1)");
  sheet.getRange("I25").setValue(3);
  sheet.getRange("K25").setValue("A(2)   ->   D(2)   ->   G(2)   ->   J(2)   ->   M(3)   ->   O(2)");
  sheet.getRange("L25").setValue("D(2)");
  sheet.getRange("M25").setValue("G(2)");
  sheet.getRange("N25").setValue("J(2)");
  sheet.getRange("O25").setValue("M(3)");
  sheet.getRange("P25").setValue("O(2)");
  sheet.getRange("B26").setValue(2);
  sheet.getRange("C26").setValue("A(2)");
  sheet.getRange("D26").setValue("D(2)");
  sheet.getRange("E26").setValue("E(1)");
  sheet.getRange("I26").setValue(5);
  sheet.getRange("K26").setValue("Với tổng độ dài đường găng là 13 ngày làm việc (Critical Path = 13 ngày)");
  sheet.getRange("B27").setValue(3);
  sheet.getRange("C27").setValue("A(2)");
  sheet.getRange("D27").setValue("D(2)");
  sheet.getRange("E27").setValue("F(1)");
  sheet.getRange("I27").setValue(5);
  sheet.getRange("B28").setValue(4);
  sheet.getRange("C28").setValue("A(2)");
  sheet.getRange("D28").setValue("D(2)");
  sheet.getRange("E28").setValue("G(2)");
  sheet.getRange("F28").setValue("H(1)");
  sheet.getRange("I28").setValue(7);
  sheet.getRange("B29").setValue(5);
  sheet.getRange("C29").setValue("A(2)");
  sheet.getRange("D29").setValue("D(2)");
  sheet.getRange("E29").setValue("G(2)");
  sheet.getRange("F29").setValue("I(1)");
  sheet.getRange("I29").setValue(7);
  sheet.getRange("B30").setValue(6);
  sheet.getRange("C30").setValue("A(2)");
  sheet.getRange("D30").setValue("D(2)");
  sheet.getRange("E30").setValue("G(2)");
  sheet.getRange("F30").setValue("J(2)");
  sheet.getRange("G30").setValue("K(1)");
  sheet.getRange("I30").setValue(9);
  sheet.getRange("B31").setValue(7);
  sheet.getRange("C31").setValue("A(2)");
  sheet.getRange("D31").setValue("D(2)");
  sheet.getRange("E31").setValue("G(2)");
  sheet.getRange("F31").setValue("J(2)");
  sheet.getRange("G31").setValue("L(2)");
  sheet.getRange("I31").setValue(10);
  sheet.getRange("B32").setValue(8);
  sheet.getRange("C32").setValue("A(2)");
  sheet.getRange("D32").setValue("D(2)");
  sheet.getRange("E32").setValue("G(2)");
  sheet.getRange("F32").setValue("J(2)");
  sheet.getRange("G32").setValue("M(3)");
  sheet.getRange("H32").setValue("N(1)");
  sheet.getRange("I32").setValue(12);
  sheet.getRange("B33").setValue(9);
  sheet.getRange("C33").setValue("A(2)");
  sheet.getRange("D33").setValue("D(2)");
  sheet.getRange("E33").setValue("G(2)");
  sheet.getRange("F33").setValue("J(2)");
  sheet.getRange("G33").setValue("M(3)");
  sheet.getRange("H33").setValue("O(2)");
  sheet.getRange("I33").setValue(13);
  sheet.getRange("B34").setValue(10);
  sheet.getRange("C34").setValue("B(1)");
  sheet.getRange("D34").setValue("C(1)");
  sheet.getRange("I34").setValue(2);
  sheet.getRange("B35").setValue(11);
  sheet.getRange("C35").setValue("B(1)");
  sheet.getRange("D35").setValue("D(2)");
  sheet.getRange("E35").setValue("E(1)");
  sheet.getRange("I35").setValue(4);
  sheet.getRange("B36").setValue(12);
  sheet.getRange("C36").setValue("B(1)");
  sheet.getRange("D36").setValue("D(2)");
  sheet.getRange("E36").setValue("F(1)");
  sheet.getRange("I36").setValue(4);
  sheet.getRange("B37").setValue(13);
  sheet.getRange("C37").setValue("B(1)");
  sheet.getRange("D37").setValue("D(2)");
  sheet.getRange("E37").setValue("G(2)");
  sheet.getRange("F37").setValue("H(1)");
  sheet.getRange("I37").setValue(6);
  sheet.getRange("B38").setValue(14);
  sheet.getRange("C38").setValue("B(1)");
  sheet.getRange("D38").setValue("D(2)");
  sheet.getRange("E38").setValue("G(2)");
  sheet.getRange("F38").setValue("I(1)");
  sheet.getRange("I38").setValue(6);
  sheet.getRange("B39").setValue(15);
  sheet.getRange("C39").setValue("B(1)");
  sheet.getRange("D39").setValue("D(2)");
  sheet.getRange("E39").setValue("G(2)");
  sheet.getRange("F39").setValue("J(2)");
  sheet.getRange("G39").setValue("K(1)");
  sheet.getRange("I39").setValue(8);
  sheet.getRange("B40").setValue(16);
  sheet.getRange("C40").setValue("B(1)");
  sheet.getRange("D40").setValue("D(2)");
  sheet.getRange("E40").setValue("G(2)");
  sheet.getRange("F40").setValue("J(2)");
  sheet.getRange("G40").setValue("L(2)");
  sheet.getRange("I40").setValue(9);
  sheet.getRange("B41").setValue(17);
  sheet.getRange("C41").setValue("B(1)");
  sheet.getRange("D41").setValue("D(2)");
  sheet.getRange("E41").setValue("G(2)");
  sheet.getRange("F41").setValue("J(2)");
  sheet.getRange("G41").setValue("M(3)");
  sheet.getRange("H41").setValue("N(1)");
  sheet.getRange("I41").setValue(11);
  sheet.getRange("B42").setValue(18);
  sheet.getRange("C42").setValue("B(1)");
  sheet.getRange("D42").setValue("D(2)");
  sheet.getRange("E42").setValue("G(2)");
  sheet.getRange("F42").setValue("J(2)");
  sheet.getRange("G42").setValue("M(3)");
  sheet.getRange("H42").setValue("O(2)");
  sheet.getRange("I42").setValue(12);
  sheet.getRange("B46").setValue("3.4.2 - BẢNG ƯỚC LƯỢNG TIẾN ĐỘ PERT 3 ĐIỂM & ĐƯỜNG GĂNG TOÀN DỰ ÁN SMARTRECRUIT (08 SPRINT)");
  sheet.getRange("B48").setValue("Mã");
  sheet.getRange("C48").setValue("Tên hoạt động kỹ thuật cốt lõi (SmartRecruit)");
  sheet.getRange("D48").setValue("Tiên quyết");
  sheet.getRange("E48").setValue("O (Lạc quan)");
  sheet.getRange("F48").setValue("M (Khả năng cao)");
  sheet.getRange("G48").setValue("P (Bi quan)");
  sheet.getRange("H48").setValue("TE (ngày)");
  sheet.getRange("I48").setValue("Var (σ²)");
  sheet.getRange("J48").setValue("ES");
  sheet.getRange("K48").setValue("EF");
  sheet.getRange("L48").setValue("LS");
  sheet.getRange("M48").setValue("LF");
  sheet.getRange("N48").setValue("Slack");
  sheet.getRange("O48").setValue("Đường găng?");
  sheet.getRange("B49").setValue("A");
  sheet.getRange("C49").setValue("WBS 1.1: Khởi động dự án & khóa baseline kỹ thuật");
  sheet.getRange("D49").setValue("-");
  sheet.getRange("E49").setValue(1);
  sheet.getRange("F49").setValue(2);
  sheet.getRange("G49").setValue(3);
  sheet.getRange("H49").setValue(2);
  sheet.getRange("I49").setValue(0.111);
  sheet.getRange("J49").setValue(0);
  sheet.getRange("K49").setValue(2);
  sheet.getRange("L49").setValue(0);
  sheet.getRange("M49").setValue(2);
  sheet.getRange("N49").setValue(0);
  sheet.getRange("O49").setValue("CÓ (Găng)");
  sheet.getRange("B50").setValue("B");
  sheet.getRange("C50").setValue("WBS 1.2-1.3: Phân tích yêu cầu, SRS & State machine");
  sheet.getRange("D50").setValue("A");
  sheet.getRange("E50").setValue(2);
  sheet.getRange("F50").setValue(3);
  sheet.getRange("G50").setValue(4);
  sheet.getRange("H50").setValue(3);
  sheet.getRange("I50").setValue(0.111);
  sheet.getRange("J50").setValue(2);
  sheet.getRange("K50").setValue(5);
  sheet.getRange("L50").setValue(2);
  sheet.getRange("M50").setValue(5);
  sheet.getRange("N50").setValue(0);
  sheet.getRange("O50").setValue("CÓ (Găng)");
  sheet.getRange("B51").setValue("C");
  sheet.getRange("C51").setValue("WBS 1.4: Spike Gemini: trích xuất cấu trúc & guardrail");
  sheet.getRange("D51").setValue("A");
  sheet.getRange("E51").setValue(2);
  sheet.getRange("F51").setValue(3);
  sheet.getRange("G51").setValue(4);
  sheet.getRange("H51").setValue(3);
  sheet.getRange("I51").setValue(0.111);
  sheet.getRange("J51").setValue(2);
  sheet.getRange("K51").setValue(5);
  sheet.getRange("L51").setValue(2);
  sheet.getRange("M51").setValue(5);
  sheet.getRange("N51").setValue(0);
  sheet.getRange("O51").setValue("CÓ (Găng)");
  sheet.getRange("B52").setValue("D");
  sheet.getRange("C52").setValue("WBS 1.5: Thiết kế kiến trúc Modular Monolith & ADR");
  sheet.getRange("D52").setValue("B, C");
  sheet.getRange("E52").setValue(1);
  sheet.getRange("F52").setValue(2);
  sheet.getRange("G52").setValue(3);
  sheet.getRange("H52").setValue(2);
  sheet.getRange("I52").setValue(0.111);
  sheet.getRange("J52").setValue(5);
  sheet.getRange("K52").setValue(7);
  sheet.getRange("L52").setValue(5);
  sheet.getRange("M52").setValue(7);
  sheet.getRange("N52").setValue(0);
  sheet.getRange("O52").setValue("CÓ (Găng)");
  sheet.getRange("B53").setValue("E");
  sheet.getRange("C53").setValue("WBS 2.1-2.2: Thiết kế ERD 16 bảng & Schema Flyway");
  sheet.getRange("D53").setValue("D");
  sheet.getRange("E53").setValue(2);
  sheet.getRange("F53").setValue(3);
  sheet.getRange("G53").setValue(4);
  sheet.getRange("H53").setValue(3);
  sheet.getRange("I53").setValue(0.111);
  sheet.getRange("J53").setValue(7);
  sheet.getRange("K53").setValue(10);
  sheet.getRange("L53").setValue(7);
  sheet.getRange("M53").setValue(10);
  sheet.getRange("N53").setValue(0);
  sheet.getRange("O53").setValue("CÓ (Găng)");
  sheet.getRange("B54").setValue("F");
  sheet.getRange("C54").setValue("WBS 2.3-2.4: Design system UI & Scaffold Web/API");
  sheet.getRange("D54").setValue("D");
  sheet.getRange("E54").setValue(2);
  sheet.getRange("F54").setValue(3);
  sheet.getRange("G54").setValue(4);
  sheet.getRange("H54").setValue(3);
  sheet.getRange("I54").setValue(0.111);
  sheet.getRange("J54").setValue(7);
  sheet.getRange("K54").setValue(10);
  sheet.getRange("L54").setValue(7);
  sheet.getRange("M54").setValue(10);
  sheet.getRange("N54").setValue(0);
  sheet.getRange("O54").setValue("CÓ (Găng)");
  sheet.getRange("B55").setValue("G");
  sheet.getRange("C55").setValue("WBS 3.1 & 3.6: Auth RBAC (Google OIDC) & Admin API");
  sheet.getRange("D55").setValue("E, F");
  sheet.getRange("E55").setValue(3);
  sheet.getRange("F55").setValue(5);
  sheet.getRange("G55").setValue(7);
  sheet.getRange("H55").setValue(5);
  sheet.getRange("I55").setValue(0.444);
  sheet.getRange("J55").setValue(10);
  sheet.getRange("K55").setValue(15);
  sheet.getRange("L55").setValue(10);
  sheet.getRange("M55").setValue(15);
  sheet.getRange("N55").setValue(0);
  sheet.getRange("O55").setValue("CÓ (Găng)");
  sheet.getRange("B56").setValue("H");
  sheet.getRange("C56").setValue("WBS 3.3-3.5: Job posting API, Recruiter UI & Taxonomy");
  sheet.getRange("D56").setValue("G");
  sheet.getRange("E56").setValue(2);
  sheet.getRange("F56").setValue(4);
  sheet.getRange("G56").setValue(6);
  sheet.getRange("H56").setValue(4);
  sheet.getRange("I56").setValue(0.444);
  sheet.getRange("J56").setValue(15);
  sheet.getRange("K56").setValue(19);
  sheet.getRange("L56").setValue(16);
  sheet.getRange("M56").setValue(20);
  sheet.getRange("N56").setValue(1);
  sheet.getRange("O56").setValue("Không");
  sheet.getRange("B57").setValue("I");
  sheet.getRange("C57").setValue("WBS 4.1-4.2: Upload CV S3 private & Gemini Adapter");
  sheet.getRange("D57").setValue("G");
  sheet.getRange("E57").setValue(3);
  sheet.getRange("F57").setValue(5);
  sheet.getRange("G57").setValue(7);
  sheet.getRange("H57").setValue(5);
  sheet.getRange("I57").setValue(0.444);
  sheet.getRange("J57").setValue(15);
  sheet.getRange("K57").setValue(20);
  sheet.getRange("L57").setValue(15);
  sheet.getRange("M57").setValue(20);
  sheet.getRange("N57").setValue(0);
  sheet.getRange("O57").setValue("CÓ (Găng)");
  sheet.getRange("B58").setValue("J");
  sheet.getRange("C58").setValue("WBS 4.3-4.5: Candidate CV Intake UI & End-to-End");
  sheet.getRange("D58").setValue("H, I");
  sheet.getRange("E58").setValue(2);
  sheet.getRange("F58").setValue(3);
  sheet.getRange("G58").setValue(4);
  sheet.getRange("H58").setValue(3);
  sheet.getRange("I58").setValue(0.111);
  sheet.getRange("J58").setValue(20);
  sheet.getRange("K58").setValue(23);
  sheet.getRange("L58").setValue(20);
  sheet.getRange("M58").setValue(23);
  sheet.getRange("N58").setValue(0);
  sheet.getRange("O58").setValue("CÓ (Găng)");
  sheet.getRange("B59").setValue("K");
  sheet.getRange("C59").setValue("WBS 5.1-5.2: Match Scoring Engine & Evaluation API");
  sheet.getRange("D59").setValue("J");
  sheet.getRange("E59").setValue(3);
  sheet.getRange("F59").setValue(4);
  sheet.getRange("G59").setValue(5);
  sheet.getRange("H59").setValue(4);
  sheet.getRange("I59").setValue(0.111);
  sheet.getRange("J59").setValue(23);
  sheet.getRange("K59").setValue(27);
  sheet.getRange("L59").setValue(23);
  sheet.getRange("M59").setValue(27);
  sheet.getRange("N59").setValue(0);
  sheet.getRange("O59").setValue("CÓ (Găng)");
  sheet.getRange("B60").setValue("L");
  sheet.getRange("C60").setValue("WBS 5.3-5.5: Ranking UI, Feedback Review & Email");
  sheet.getRange("D60").setValue("K");
  sheet.getRange("E60").setValue(2);
  sheet.getRange("F60").setValue(3);
  sheet.getRange("G60").setValue(4);
  sheet.getRange("H60").setValue(3);
  sheet.getRange("I60").setValue(0.111);
  sheet.getRange("J60").setValue(27);
  sheet.getRange("K60").setValue(30);
  sheet.getRange("L60").setValue(27);
  sheet.getRange("M60").setValue(30);
  sheet.getRange("N60").setValue(0);
  sheet.getRange("O60").setValue("CÓ (Găng)");
  sheet.getRange("B61").setValue("M");
  sheet.getRange("C61").setValue("WBS 6.3-6.5: Docker hardening, Compose & CI/CD");
  sheet.getRange("D61").setValue("L");
  sheet.getRange("E61").setValue(2);
  sheet.getRange("F61").setValue(3);
  sheet.getRange("G61").setValue(4);
  sheet.getRange("H61").setValue(3);
  sheet.getRange("I61").setValue(0.111);
  sheet.getRange("J61").setValue(30);
  sheet.getRange("K61").setValue(33);
  sheet.getRange("L61").setValue(30);
  sheet.getRange("M61").setValue(33);
  sheet.getRange("N61").setValue(0);
  sheet.getRange("O61").setValue("CÓ (Găng)");
  sheet.getRange("B62").setValue("N");
  sheet.getRange("C62").setValue("WBS 7.1 & 7.4: Integration/E2E QA & Security Review");
  sheet.getRange("D62").setValue("M");
  sheet.getRange("E62").setValue(2);
  sheet.getRange("F62").setValue(3);
  sheet.getRange("G62").setValue(4);
  sheet.getRange("H62").setValue(3);
  sheet.getRange("I62").setValue(0.111);
  sheet.getRange("J62").setValue(33);
  sheet.getRange("K62").setValue(36);
  sheet.getRange("L62").setValue(33);
  sheet.getRange("M62").setValue(36);
  sheet.getRange("N62").setValue(0);
  sheet.getRange("O62").setValue("CÓ (Găng)");
  sheet.getRange("B63").setValue("P");
  sheet.getRange("C63").setValue("WBS 8.1-8.5: AWS Deploy, Observability & UAT Handover");
  sheet.getRange("D63").setValue("N");
  sheet.getRange("E63").setValue(2);
  sheet.getRange("F63").setValue(3);
  sheet.getRange("G63").setValue(4);
  sheet.getRange("H63").setValue(3);
  sheet.getRange("I63").setValue(0.111);
  sheet.getRange("J63").setValue(36);
  sheet.getRange("K63").setValue(39);
  sheet.getRange("L63").setValue(36);
  sheet.getRange("M63").setValue(39);
  sheet.getRange("N63").setValue(0);
  sheet.getRange("O63").setValue("CÓ (Găng)");
  sheet.getRange("B65").setValue("KẾT LUẬN ĐƯỜNG GĂNG & ĐỘ LỆCH CHUẨN TOÀN DỰ ÁN SMARTRECRUIT (SPRINT 1 - 8):");
  sheet.getRange("B66").setValue("Đường găng dự án (Critical Path):");
  sheet.getRange("G66").setValue("A → B/C → D → E/F → G → I → J → K → L → M → N → P (14 hoạt động găng, Slack = 0)");
  sheet.getRange("B67").setValue("Tổng thời gian kỳ vọng hoàn thành dự án:");
  sheet.getRange("G67").setValue("TE_project = 39.0 ngày làm việc (với hạn mức 40 ngày làm việc của 08 Sprint, dự phòng 1.0 ngày trước ngày 03/11)");
  sheet.getRange("B68").setValue("Phương sai đường găng (Variance σ²_CP):");
  sheet.getRange("G68").setValue("σ²_CP = 0.111*12 + 0.444*2 = 2.222");
  sheet.getRange("B69").setValue("Độ lệch chuẩn đường găng (Standard Dev σ_CP):");
  sheet.getRange("G69").setValue("σ_CP = √2.222 ≈ 1.491 ngày làm việc");
  sheet.getRange("B70").setValue("Xác suất hoàn thành đúng hạn 40 ngày làm việc (08 Sprint):");
  sheet.getRange("G70").setValue("Z = (40 - 39.0) / 1.491 = +0.67  ==>  P(Z ≤ 0.67) ≈ 74.86%");
  sheet.getRange("B71").setValue("Xác suất hoàn thành trước cột mốc đóng dự án 03/11/2026 (ngày 41):");
  sheet.getRange("G71").setValue("Z = (41 - 39.0) / 1.491 = +1.34  ==>  P(Z ≤ 1.34) ≈ 90.99%");
  SpreadsheetApp.flush();
}